# Introduction
Name : Syed Waleed Hussain
Email : syedwaleedhussain11@gmail.com
DHC ID : 2057

# Heart Disease Prediction

Import Libraries

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

Import Dataset

In [2]:
df = pd.read_csv('/content/cleaned_merged_heart_dataset.csv')

Performing EDA

In [3]:
df.head()

   age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [4]:
df.tail()

      age  sex  cp  trestbps  chol  ...  oldpeak  slope  ca  thal  target
1883   60    1   0       140   207  ...      1.9      2   1     3       0
1884   46    1   0       140   311  ...      1.8      1   2     3       0
1885   59    1   3       134   204  ...      0.8      2   2     2       0
1886   54    1   1       154   232  ...      0.0      2   1     2       0
1887   53    1   0       110   335  ...      3.0      1   1     3       0

[5 rows x 14 columns]

In [7]:
df.shape

(1888, 14)

In [5]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalachh    0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1888 entries, 0 to 1887
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1888 non-null   int64
 1   sex       1888 non-null   int64
 2   cp        1888 non-null   int64
 3   trestbps  1888 non-null   int64
 4   chol      1888 non-null   int64
 5   fbs       1888 non-null   int64
 6   restecg   1888 non-null   int64
 7   thalachh  1888 non-null   int64
 8   exang     1888 non-null   int64
 9   oldpeak   1888 non-null   float64
 10  slope     1888 non-null   int64
 11  ca        1888 non-null   int64
 12  thal      1888 non-null   int64
 13  target    1888 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 206.6 KB

In [8]:
df.describe()

               age          sex  ...         thal       target
count  1888.000000  1888.000000  ...  1888.000000  1888.000000
mean     54.354343     0.688559  ...     2.662606     0.517479
std       9.081505     0.463205  ...     1.249924     0.499827
min      29.000000     0.000000  ...     0.000000     0.000000
25%      47.750000     0.000000  ...     2.000000     0.000000
50%      55.000000     1.000000  ...     2.000000     1.000000
75%      61.000000     1.000000  ...     3.000000     1.000000
max      77.000000     1.000000  ...     7.000000     1.000000

[8 rows x 14 columns]

In [9]:
df['target'].value_counts()

target
1    977
0    911
Name: count, dtype: int64

Here 1 Represents Defective Heart and
0 Represents Healthy Heart

Splitting the dataset into features and target columns

In [11]:
x = df.drop(columns = 'target', axis = 1)
y = df['target']

In [12]:
print(x)

      age  sex  cp  trestbps  chol  ...  exang  oldpeak  slope  ca  thal
0      63    1   3       145   233  ...      0      2.3      0   0     1
1      37    1   2       130   250  ...      0      3.5      0   0     2
2      41    0   1       130   204  ...      0      1.4      2   0     2
3      56    1   1       120   236  ...      0      0.8      2   0     2
4      57    0   0       120   354  ...      1      0.6      2   0     2
...   ...  ...  ..       ...   ...  ...    ...      ...    ...  ..   ...
1883   60    1   0       140   207  ...      1      1.9      2   1     3
1884   46    1   0       140   311  ...      1      1.8      1   2     3
1885   59    1   3       134   204  ...      0      0.8      2   2     2
1886   54    1   1       154   232  ...      0      0.0      2   1     2
1887   53    1   0       110   335  ...      1      3.0      1   1     3

[1888 rows x 13 columns]

In [13]:
print(y)

0       1
1       1
2       1
3       1
4       1
       ..
1883    0
1884    0
1885    0
1886    0
1887    0
Name: target, Length: 1888, dtype: int64

Splittng the dataset into train and test dataset

In [14]:
x_train,x_test,y_train,y_test = train_test_split(x , y , test_size = 0.2 , stratify=y , random_state=2)

In [15]:
print(x.shape, x_train.shape, x_test.shape)

(1888, 13) (1510, 13) (378, 13)

In [16]:
print(y.shape,y_train.shape, y_test.shape)

(1888,) (1510,) (378,)

Training The model "Logistic Regression

In [17]:
model = LogisticRegression()

In [18]:
model.fit(x_train , y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Model Evaluation

Accuracy on training data

In [20]:
x_train_prediction = model.predict(x_train)
train_accuracy = accuracy_score(x_train_prediction , y_train)

print("Accuracy on X_train dataset is :", train_accuracy)

Accuracy on X_train dataset is : 0.7649006622516556

Accuracy score on Test dataset

In [21]:
x_test_prediction = model.predict(x_test)
test_accuracy = accuracy_score(x_test_prediction , y_test)

print("Accuracy on X_test dataset is :", test_accuracy)

Accuracy on X_test dataset is : 0.746031746031746

Building Predictive System

In [26]:
input_data = (52,1,1,120,325,0,1,172,0,0.2,2,0,2)
input_data_into_numpy_array = np.asarray(input_data)
input_data_reshape = input_data_into_numpy_array.reshape(1,-1)

prediction = model.predict(input_data_reshape)
print(prediction)

if (prediction[0] == 0):
  print("Patient's heart is healthy")
else:
  print("Patient has heart disease")

[1]
Patient has heart disease

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(